#!/usr/bin/env python3
import os
import sys
import subprocess
from saxlib.si_installer import install_library, list_libraries

def main():
    if len(sys.argv) == 1:
        # Menampilkan pustaka yang tersedia
        list_libraries()
    elif len(sys.argv) == 2:
        # Install pustaka
        library_name = sys.argv[1]
        install_library(library_name)
    else:
        print("Usage: si <library-name>")
        sys.exit(1)

if __name__ == "__main__":
    main()
